def show_menu():
        print("Please select a number from the menu below: ")
        print("1. Add a new student")
        print("2. Delete an existing student")
        print("3. Display current students list")
        print("4. Show overall grades average")
        print("5. Show top 3 students with higher grades average")
        print("6. Display students with failed grades")
        print("7. Export students list to CSV")
        print("8. Import list from existing CSV")
        print("9. Exit this menu")