CREATE TABLE Products (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Price NUMERIC(10,2) NOT NULL,
    Stock INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE Users (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE Bills (
    ID SERIAL PRIMARY KEY,
    UserID INTEGER NOT NULL REFERENCES Users(ID),
    Status VARCHAR(20) NOT NULL DEFAULT 'Active',
    Created_At TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE Bill_Products (
    ID SERIAL PRIMARY KEY,
    BillID INTEGER NOT NULL REFERENCES Bills(ID),
    ProductID INTEGER NOT NULL REFERENCES Products(ID),
    Quantity INTEGER NOT NULL
);